plugins {
    id 'java'
}

group = 'com.vividflash'
version = '1.1.1'

def runeLiteVersion = '1.12.36'

repositories {
    mavenLocal()
    maven {
        url = 'https://repo.runelite.net'
    }
    mavenCentral()
}

dependencies {
    compileOnly group: 'net.runelite', name: 'client', version: runeLiteVersion
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.release = 11
}
