displayName=Better Slayer
author=vividflash
description=Mortimer task odds, master rules, task sorting, Nieve
tags=slayer,nieve,mortimer,task,boost
plugins=com.vividflash.slayer.SlayerPlugin
build=standard
version=1.2.1
